// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4rD14y19MdhjIXyhMmmk0y2aMbSXN-a0',
    appId: '1:752196246605:web:bb54570a75213d808dd004',
    messagingSenderId: '752196246605',
    projectId: 'velocitygo-azlan',
    authDomain: 'velocitygo-azlan.firebaseapp.com',
    storageBucket: 'velocitygo-azlan.firebasestorage.app',
    measurementId: 'G-RMFSVM3078',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUNvFssXevUqVUcmzzo1ibsvFmni5dqk',
    appId: '1:752196246605:android:9e9999352367d8028dd004',
    messagingSenderId: '752196246605',
    projectId: 'velocitygo-azlan',
    storageBucket: 'velocitygo-azlan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcRdUmds_xN4WK4iCs6V-HKAPRCo_6CYA',
    appId: '1:752196246605:ios:9156e24a77cdd5158dd004',
    messagingSenderId: '752196246605',
    projectId: 'velocitygo-azlan',
    storageBucket: 'velocitygo-azlan.firebasestorage.app',
    androidClientId: '752196246605-je106tcvletahj3rgo5f2vo2t274tnk3.apps.googleusercontent.com',
    iosClientId: '752196246605-0s3p4dioejmb2mafbgk4j0gia4k4om8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalvel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcRdUmds_xN4WK4iCs6V-HKAPRCo_6CYA',
    appId: '1:752196246605:ios:9156e24a77cdd5158dd004',
    messagingSenderId: '752196246605',
    projectId: 'velocitygo-azlan',
    storageBucket: 'velocitygo-azlan.firebasestorage.app',
    androidClientId: '752196246605-je106tcvletahj3rgo5f2vo2t274tnk3.apps.googleusercontent.com',
    iosClientId: '752196246605-0s3p4dioejmb2mafbgk4j0gia4k4om8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalvel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4rD14y19MdhjIXyhMmmk0y2aMbSXN-a0',
    appId: '1:752196246605:web:51c3dd70577c4ad98dd004',
    messagingSenderId: '752196246605',
    projectId: 'velocitygo-azlan',
    authDomain: 'velocitygo-azlan.firebaseapp.com',
    storageBucket: 'velocitygo-azlan.firebasestorage.app',
    measurementId: 'G-YRP3DQMFDT',
  );

}